version: '2'
services:
  nginx:
    image: 'fabiocinicolo/ping-web-app:latest'
    stdin_open: true
    tty: true
    ports:
      - '80:80'
    networks:
      developers_net:
        ipv4_address: 192.168.20.51
      employees_net:
        ipv4_address: 192.168.30.20
      public_net:
        ipv4_address: 192.168.10.69
  attacker:
    image: 'fabiocinicolo/kali-shellinabox:latest'
    stdin_open: true
    tty: true
    ports:
      - '4200:4200'
    networks:
      public_net:
        ipv4_address: 192.168.10.35
  API:
    image: 'fabiocinicolo/ping-api:latest'
    stdin_open: true
    tty: true
    ports:
      - '8080:8080'
    networks:
      developers_net:
        ipv4_address: 192.168.20.52
  host-2:
    image: 'fabiocinicolo/employee-host-2:latest'
    stdin_open: true
    tty: true
    ports:
      - '2202:22'
    networks:
      employees_net:
        ipv4_address: 192.168.30.22
  host-1:
    image: 'fabiocinicolo/employee-host-1:latest'
    stdin_open: true
    tty: true
    ports:
      - '6080:80'
    networks:
      employees_net:
        ipv4_address: 192.168.30.21
  dashboard:
    image: 'fabiocinicolo/admin-dashboard:latest'
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    networks:
      developers_net:
        ipv4_address: 192.168.20.53
networks:
  public_net:
    ipam:
      config:
        - subnet: 192.168.10.1/24
  developers_net:
    ipam:
      config:
        - subnet: 192.168.20.1/24
  employees_net:
    ipam:
      config:
        - subnet: 192.168.30.1/24
